### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by kanetjuh** [FivePixels/Tribble#16] opened 2022-11-29 08:56 UTC
This happens after I open the payment ticket and press the agree emoji/button.
![image](https://user-images.githubusercontent.com/50002439/204483752-9baf96b6-3cb1-4f9e-bdae-d96c8938089c.png)

**Comment by kanetjuh** [comment] 2022-11-29 08:58
Note: This happens when I disable the TOS, and make a new ticket.
![image](https://user-images.githubusercontent.com/50002439/204484378-1c01bead-b402-4193-b9f7-c455b5bfb299.png)

**Comment by FivePixels** [comment] 2022-11-29 21:17
Yep, this is due to discord.js-menu not supporting the latest version of discord.js and Discord's new endpoint URIs. This will be fixed with #13.

**Comment by FivePixels** [comment] 2023-01-10 22:57
@kanetjuh #13 has been resolved. Will be closing this issue if it cannot be reproduced.

**Closed** 2023-01-16 13:16 UTC
